// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package transformxml.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.PipedInputStream;
import java.io.PipedOutputStream;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import javax.xml.transform.stream.StreamSource;
import org.w3c.dom.Document; 

public class Transform extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __XmlFile;
	private system.proxies.FileDocument XmlFile;
	private IMendixObject __XsltFile;
	private system.proxies.FileDocument XsltFile;
	private IMendixObject __OutputFile;
	private system.proxies.FileDocument OutputFile;

	public Transform(IContext context, IMendixObject XmlFile, IMendixObject XsltFile, IMendixObject OutputFile)
	{
		super(context);
		this.__XmlFile = XmlFile;
		this.__XsltFile = XsltFile;
		this.__OutputFile = OutputFile;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.XmlFile = __XmlFile == null ? null : system.proxies.FileDocument.initialize(getContext(), __XmlFile);

		this.XsltFile = __XsltFile == null ? null : system.proxies.FileDocument.initialize(getContext(), __XsltFile);

		this.OutputFile = __OutputFile == null ? null : system.proxies.FileDocument.initialize(getContext(), __OutputFile);

		// BEGIN USER CODE
		DocumentBuilderFactory documentBuilderFactory = DocumentBuilderFactory.newInstance();
		DocumentBuilder builder = documentBuilderFactory.newDocumentBuilder();
		TransformerFactory transformerFactory = TransformerFactory.newInstance();

		try (InputStream xmlStream = Core.getFileDocumentContent(getContext(), __XmlFile)) {
			try (InputStream xsltStream = Core.getFileDocumentContent(getContext(), __XsltFile)) {		
				Document document = builder.parse(xmlStream);
				DOMSource source = new DOMSource(document);
				
				StreamSource stylesource = new StreamSource(xsltStream);
				Transformer transformer = transformerFactory.newTransformer(stylesource);

				try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
					StreamResult result = new StreamResult(outputStream);

					transformer.transform(source, result);
					outputStream.flush();
					
					try (ByteArrayInputStream inputStream = new ByteArrayInputStream(outputStream.toByteArray())) {
						Core.storeFileDocumentContent(getContext(), __OutputFile, inputStream);
					}
				}
			}
		}
		
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Transform";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
